### ISSUE TITLE
ngx Linky fails to compile

### ISSUE THREAD

**Issue by atotalnoob** [dzonatan/angular2-linky#10]
Hi I added the package via npm i --save ngx-linky
Installed version 2.1.0

I added linkyModule to the module in question. 

I then used linky in a component
<span [innerHTML]="msg | linky"></span>

I ran the application and it failed to compile.

Error: Can't Resolve 'autolinker' in PathTongxLinky

**Comment by dzonatan** [comment]
Seems like you forgot to add peer dependency `autolinker`.
`npm i autolinker`.
