### ISSUE TITLE
Support for angular 8

### ISSUE THREAD

**Issue by arman-g** [dzonatan/angular2-linky#11]
Angular v8.2.2

First I want to thank you for the great library. After I upgraded to angular 8 I am getting the following warning below.

npm WARN ngx-linky@2.1.0 requires a peer of @angular/common@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by dzonatan** [comment]
released a `v2.2.0`
