### ISSUE TITLE
Alternatives to Autolinker

### ISSUE THREAD

**Issue by marcalj** [dzonatan/angular2-linky#2]
Hi, thanks for your work! I'm having a problem with Autolinker and wondering if there's another library to use if they can't fix the issue.
https://github.com/gregjacobs/Autolinker.js/issues/165

Thanks!

**Comment by gregjacobs** [comment]
Hey, just an fyi, I'm the author of Autolinker and I fixed the issue that @marcalj was experiencing in v0.27.0 

Thanks for using my project - hope it's been helpful, and let me know if you ever need anything!

**Comment by dzonatan** [comment]
Thanks @gregjacobs ! :beer: 

I'm closing the issue since it's fixed.

**Comment by marcalj** [comment]
@dzonatan Please, to close the issue, merge this pull request, thanks!
https://github.com/dzonatan/angular2-linky/pull/3

**Comment by dzonatan** [comment]
The actual dependency to autolinker.js is on [this line](https://github.com/dzonatan/angular2-linky/blob/master/package.json#L29). So it should always take the newest version.

Anyway thanks for you contribution! ;)

**Comment by marcalj** [comment]
Oh sorry! Thanks!
