### ISSUE TITLE
Missing dependencies: autolinker

### ISSUE THREAD

**Issue by cichy380** [dzonatan/angular2-linky#27]
When I try to start my project I got:
```
An unhandled exception occurred: The target entry-point "ngx-linky" has missing dependencies:
 - autolinker
```

**Comment by dzonatan** [comment]
Have you installed a required peer dependency?
`npm i autolinker`

**Comment by lyvyu** [comment]
Hey, I also have this problem.
Shouldn't autolinker be installed automatically when installing ngx-linky ?! 

Thanks in advance.

**Comment by cichy380** [comment]
Yes, and it works, but I think it should be installed automatically if it is required dependency : )

**Comment by dzonatan** [comment]
It's a good practice to keep it as peer dependency to have a better control over the version of `autolinker`.

However, from npm v7 peer dependencies are automatically installed.
