### ISSUE TITLE
Angular 7 Error

### ISSUE THREAD

**Issue by enniob** [dzonatan/angular2-linky#8]
I'm trying to install your component and when I build for development I get the following error.

```
ERROR in ./node_modules/ngx-linky/fesm5/ngx-linky.js
Module not found: Error: Can't resolve 'autolinker' in 'D:\fffff\fffff\angular\node_modules\ngx-linky\fesm5'
```

I'm using the latest version of Angular 7.1 on my application.

**Comment by enniob** [comment]
so I guess the Autolinker.js file was not installed when I installed the package. I manually installed the Autolinker.js and it is working now.

**Comment by dzonatan** [comment]
Yes, you need to install `autolinker` dependency manually.
You should have got a warning regarding missing peer dependency.
